version: '2'
services:
  db:
    image: neo4j:3.5-enterprise
    container_name: vcf2neo-db
    volumes_from:
      - dc:rw
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_dbms_allow__format__migration: 'true'
      NEO4J_dbms_allow__upgrade: 'true'
    ports:
      - "7687:7687"
      - "7474:7474"
    depends_on:
      - dc
  dc:
    build: dc/
    container_name: vcf2neo-dc
