{% set version = "0.0.7" %}
{% set sha256 = "84c67f7dd6760744a215115bf8284eed92130e9bd4624b22e7bb5a57a0dbd36a" %}
{% set py2neo = "3.1.2" %}

package:
  name: vcf2neo
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/vcf2neo/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0


requirements:
  host:
    - python
    - pip
    - click
    - py2neo {{ py2neo }}
    - tqdm
    - biopython
    - bioservices
  run:
    - python
    - click
    - py2neo {{ py2neo }}
    - tqdm
    - biopython
    - bioservices

test:
  imports:
    - vcf2neo
  commands:
    - vcf2neo |& grep vcf2neo

about:
  home: https://github.com/COMBAT-TB/vcf2neo
  license_file: LICENSE
  summary: 'Parses SnpEff annotated VCF files to a Neo4j Graph database..'
  dev_url: https://github.com/COMBAT-TB/vcf2neo
